using Microsoft.EntityFrameworkCore;
using ParkingApiPg.Data;
using ParkingApiPg.Services;

// Be lenient about DateTime kinds so DateTime.Now works with PostgreSQL 'timestamp' columns
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddDbContext<ParkingDbContext>(o =>
    o.UseNpgsql(builder.Configuration.GetConnectionString("Default")));
builder.Services.AddCors(o => o.AddDefaultPolicy(p =>
    p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddHttpClient();   // for pulling from an external parking-system REST API

// connector + platform settings + scheduled sync
builder.Services.AddTransient<IngestionService>();      // transient: resolvable from the background service's root provider
builder.Services.AddTransient<AggregationService>();    // rebuilds summary tables from imported data
builder.Services.AddSingleton<SettingsService>();       // cached platform settings
builder.Services.AddHostedService<SyncBackgroundService>();

var app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI();
app.UseCors();
app.UseDefaultFiles();
app.UseStaticFiles();

// API-key gate for /api/*
// - /api/gate/* accepts a per-device key (X-Device-Key, from Gate_Devices) or the master key
// - everything else under /api requires the master X-Api-Key
app.Use(async (ctx, next) =>
{
    if (ctx.Request.Path.StartsWithSegments("/api"))
    {
        var master = app.Configuration["ApiKey"];
        var hasMaster = ctx.Request.Headers.TryGetValue("X-Api-Key", out var key) && key == master;

        if (ctx.Request.Path.StartsWithSegments("/api/gate"))
        {
            if (ctx.Request.Headers.TryGetValue("X-Device-Key", out var devKey))
            {
                var db = ctx.RequestServices.GetRequiredService<ParkingDbContext>();
                var dk = devKey.ToString();
                var device = await db.GateDevices
                    .FirstOrDefaultAsync(d => d.Api_Key == dk && d.Is_Active);
                if (device != null)
                {
                    ctx.Items["DeviceId"] = device.Device_ID;
                    await next();
                    return;
                }
            }
            if (hasMaster)
            {
                ctx.Items["DeviceId"] = "master-key";
                await next();
                return;
            }
            ctx.Response.StatusCode = 401;
            await ctx.Response.WriteAsJsonAsync(new { error = "Missing or invalid X-Device-Key (or master X-Api-Key) header" });
            return;
        }

        if (!hasMaster)
        {
            ctx.Response.StatusCode = 401;
            await ctx.Response.WriteAsJsonAsync(new { error = "Missing or invalid X-Api-Key header" });
            return;
        }
    }
    await next();
});

app.MapControllers();

// create the Live_Parking table on first run (historical tables already exist);
// the gate tables are created explicitly because EnsureCreated skips an existing DB
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ParkingDbContext>();
    db.Database.EnsureCreated();
    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "Gate_Devices" (
            "Device_ID" text PRIMARY KEY,
            "Api_Key"   text NOT NULL,
            "Gate_Type" text NOT NULL DEFAULT 'entry',
            "Location"  text NOT NULL DEFAULT '',
            "Is_Active" boolean NOT NULL DEFAULT true
        );
        CREATE TABLE IF NOT EXISTS "Gate_Log" (
            "Id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Log_Time"   timestamp NOT NULL,
            "Device_ID"  text NOT NULL DEFAULT '',
            "Plate"      text NOT NULL DEFAULT '',
            "Action"     text NOT NULL DEFAULT '',
            "Reason"     text NOT NULL DEFAULT '',
            "Ticket_ID"  text NOT NULL DEFAULT '',
            "Confidence" double precision NULL
        );
        CREATE TABLE IF NOT EXISTS "Gate_Payments" (
            "Id"        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Ticket_ID" text NOT NULL,
            "Amount"    numeric NOT NULL,
            "Paid_At"   timestamp NOT NULL,
            "Method"    text NOT NULL DEFAULT 'Autopay'
        );
        INSERT INTO "Gate_Devices" ("Device_ID", "Api_Key", "Gate_Type", "Location") VALUES
            ('ENTRY-CAM-01', 'gate-entry-01-key-7f3a', 'entry', 'North entrance, ground level'),
            ('EXIT-CAM-01',  'gate-exit-01-key-9b2c',  'exit',  'North exit, ground level')
        ON CONFLICT ("Device_ID") DO NOTHING;

        -- saved connection + field mapping to an external parking system's database
        CREATE TABLE IF NOT EXISTS "Data_Source_Config" (
            "Id"          int PRIMARY KEY DEFAULT 1,
            "Config_Json" text NOT NULL DEFAULT '',
            "Last_Sync"   timestamptz NULL,
            "Last_Status" text NOT NULL DEFAULT 'never synced'
        );
        -- platform-side settings (capacity, tariff, auto-sync interval)
        CREATE TABLE IF NOT EXISTS "App_Settings" (
            "Key"   text PRIMARY KEY,
            "Value" text NOT NULL
        );
        """);
    // load settings once at startup so the configurable tariff is applied
    scope.ServiceProvider.GetRequiredService<SettingsService>().Reload();
}

app.Run();
